### ISSUE TITLE
本人打算在研究中使用您团队的数据集，希望征得您的同意

### ISSUE THREAD

**Issue by DDshimakaze** [JACYI/Dataset-for-Remote-Sensing#1]
老师您好，我是武汉大学测国重实验室的一名研究生，正在做遥感影像飞机目标细粒度识别相关的研究，有幸拜读了您的《MHA-CNN: AIRCRAFT FINE-GRAINED RECOGNITION OF REMOTE SENSING IMAGE BASED ON MULTIPLE HIERARCHIES ATTENTION》论文，目前打算在研究中使用您团队的数据集Aircraft-16，但似乎没有看到公开的网站。

1. 请问我们团队可以在实验和论文中使用该数据集吗？
2. 请问GitHub上的这个Aircraft-16数据集是论文里的版本吗？
3. 请问引用该数据集的格式是怎么样的呢？

**Comment by JACYI** [comment]
您好，我已经更新了我的github仓库Dataset-for-Remote-Sensing的README.md文件中数据集（Aircraft-16）引用描述信息。您的团队可以在引用了该论文的前提下使用本数据集并发表相关论文。


对你的问题的回答：
1. 本数据集可以被公开使用；
2. Github上的数据集与您提到的论文中数据集一致，包括训练集和测试集的划分；
3. 格式请查看README.md文件中的引用信息。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JACYI/Dataset-for-Remote-Sensing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 下午3:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JACYI/Dataset-for-Remote-Sensing] 本人打算在研究中使用您团队的数据集，希望征得您的同意 (Issue #1)





 
老师您好，我是武汉大学测国重实验室的一名研究生，正在做遥感影像飞机目标细粒度识别相关的研究，有幸拜读了您的《MHA-CNN: AIRCRAFT FINE-GRAINED RECOGNITION OF REMOTE SENSING IMAGE BASED ON MULTIPLE HIERARCHIES ATTENTION》论文，目前打算在研究中使用您团队的数据集Aircraft-16，但似乎没有看到公开的网站。
  
请问我们团队可以在实验和论文中使用该数据集吗？
 
请问GitHub上的这个Aircraft-16数据集是论文里的版本吗？
 
请问引用该数据集的格式是怎么样的呢？

**Comment by DDshimakaze** [comment]
好的，感谢您的答复与授权，谢谢老师！
